development:
  adapter: postgresql
  database: oodoo_dev
  host: localhost
  username: postgres
  password: jhlive
test:
  adapter: postgresql
  database: oodoo_test
  host: localhost
  username: postgres
  password: jhlive

production:
  adapter: postgresql
  database: oodoo_prod
  host: localhost
  username: postgres
  password: jhlive